apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  CLUSTER_NAME: {{ .Values.config.clusterName | quote }}
  CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
  ADDR: {{ .Values.config.addr | quote }}
